#!/bin/bash
# This are helper function to build the docker files

buildknock(){
	docker build -f ../dockerfiles/knock/Dockerfile -t nahidupa/knock:01 ../dockerfiles/knock/  
}

testrunknock(){
	docker  run -it \
		nahidupa/knock:01 "$@" 
}
